MST
gunrock/essentials pull request #127
Opened 2022-03-22 21:03 UTC by annielytical

2022-03-22 23:59 UTC, neoblizz requested changes
This is really well done! Great job @annielytical! We can do a few more performance passes after it is merged (I can handle some of that on my own while you move on to other things). The only main concern I have is that you're using an edge-frontier, which works because it is all index-based accessing, but is technically not supported in the back-end. Can you just create an issue for this? "Add complete support for edge-based frontiers", it will require minor changes but should become a bit more foolproof.

Rest of the stuff looks great. Most of my comments should be an easy fix.

2022-03-22 23:59 UTC, neoblizz commented on examples/algorithms/mst/mst.cu
> +};
This is great! An option to avoid CPU reference code will be nice when you just want to test for performance.
- `--validate` for example.

2022-03-22 23:59 UTC, neoblizz commented on examples/algorithms/mst/mst.cu
> +  printf("GPU MST Weight: %f\n", h_mst_weight[0]);
Minor thing, can you replace this with `std::cout`?

2022-03-22 23:59 UTC, neoblizz commented on examples/algorithms/mst/mst.cu
> +  printf("CPU MST Weight: %f\n", cpu_mst_weight);
`std::cout` instead of `printf`

2022-03-22 23:59 UTC, neoblizz commented on include/gunrock/algorithms/mst.hxx
> + * @author Muhammad Osama (mosama@ucdavis.edu)
Remove my name. This is your contribution, I am just reviewing. 😊

2022-03-22 23:59 UTC, neoblizz commented on include/gunrock/algorithms/mst.hxx
> +  thrust::device_vector<int> mst;
Can we use appropriate types for these vectors, such as `edge_t` instead of `int`. Wherever it makes sense.

2022-03-22 23:59 UTC, neoblizz commented on include/gunrock/algorithms/mst.hxx
> +                     false);
Why are these `thrust::sequence`? You should be just filling in one element there.

2022-03-22 23:59 UTC, neoblizz commented on include/gunrock/algorithms/mst.hxx
> +                     false);
`mst_edges` needs to be reset too (to `0`?)

2022-03-22 23:59 UTC, neoblizz commented on include/gunrock/algorithms/mst.hxx
> +    operators::filter::execute<operators::filter_algorithm_t::remove>(
`filter_algorithm_t::bypass` maybe faster, you can play around with this to see.

2022-03-22 23:59 UTC, neoblizz commented on include/gunrock/algorithms/mst.hxx
> +      printf("Error: invalid graph (super vertices not decremented)\n");
Throw an exception? See: https://github.com/gunrock/essentials/blob/master/include/gunrock/error.hxx#L42-L45

2022-03-23 03:56 UTC, annielytical commented
Thank you! Everything mentioned above should be fixed in the latest commit. 

The only thing I didn't change was filter::remove (I tested filter::bypass vs filter::remove and remove won).

2022-03-23 04:15 UTC, merged